import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, {useState, useEffect, useRef} from 'react';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import {alpha, createTheme, styled} from '@mui/material/styles';
import WSTable from '../../components/WSTable';
import {GetStaticProps} from 'next';
import CopyButton from '../../components/CopyButton';
import Typography from '@mui/material/Typography';
import Grid from '@mui/material/Grid';
import ReactGA from "react-ga4";
import { useRouter } from 'next/router';

// Create a react input component that accepts a column to enter the month and year and displays the dates of the month in a table.
interface HomeProps {
    initialData: any; // Change "any" to the type of your data
}

const Home: React.FC<HomeProps> = () => {
    const currentDate = new Date();
    const [data, setData] = useState(null);
    const [startDate, setStartDate] = useState<Date>(new Date(currentDate.getFullYear(), currentDate.getMonth(), 1));
    const [endDate, setEndDate] = useState<Date>(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0));

    const tableRef = useRef<HTMLDivElement>(null);
    const router = useRouter();

    ReactGA.initialize("G-MQ19L50V11");
    ReactGA.send({ hitType: "pageview", page: router.pathname, title: "Stupid timesheet" });

    const formatDateForInput = (date: Date) => {
        return date.toISOString().split('T')[0];
    };

    const handleStartDateChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setStartDate(new Date(event.target.value));
    };

    const handleEndDateChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setEndDate(new Date(event.target.value));
    };

    useEffect(() => {
        async function fetchData() {
            try {
                const response = await fetch('https://jolly-block-1d9c.woponi.workers.dev/');
                const data = await response.json();
                console.log('data = ', data);
                setData(data.vcalendar[0].vevent);
            } catch (e) {
                console.log('error = ', e);
            }
        }

        fetchData();
    }, []);

    return (
        <>
            <Head>
                <title>Stupid Timesheet for HKG</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Typography variant="h3" gutterBottom>
                    VF Timesheet generator for HKG
                </Typography>
                <Typography variant="h6" gutterBottom>
                    How to use:<br/>
                    1. Select the start and end dates for your timesheet period<br/>
                    2. Click the Copy button and paste it to the timesheet date header<br/>
                </Typography>
                <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
                    <TextField
                        label="Start Date"
                        type="date"
                        value={formatDateForInput(startDate)}
                        onChange={handleStartDateChange}
                        InputLabelProps={{
                            shrink: true,
                        }}
                    />
                    <TextField
                        label="End Date"
                        type="date"
                        value={formatDateForInput(endDate)}
                        onChange={handleEndDateChange}
                        InputLabelProps={{
                            shrink: true,
                        }}
                    />
                </Box>
                {data ?
                    <>
                        <CopyButton
                            componentToCopy={
                                <WSTable 
                                    data={data}
                                    startDate={startDate}
                                    endDate={endDate}
                                />
                            }
                        />
                    </>
                    :
                    <p>Loading data...</p>
                }
                <div className={styles.grid}>

                </div>
                
                <footer className={styles.footer}>
                    Powered by <a target={'_blank'} href={'https://github.com/woponi/worksheet_creator/'}>Pong Github</a> <br/>HK Public holiday data from <a href="https://www.1823.gov.hk/common/ical/en.json" target="_blank">1823.gov.hk</a>
                </footer>
            </main>
        </>
    )
}

export default Home