import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, {useState, useEffect, useRef} from 'react';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import {alpha, styled} from '@mui/material/styles';
import WSTable from '../../components/WSTable';
import {GetStaticProps} from 'next';

const inter = Inter({subsets: ['latin']})

// Create a react input component that accepts a column to enter the month and year and displays the dates of the month in a table.
interface HomeProps {
    initialData: any; // Change "any" to the type of your data
}

const Home: React.FC<HomeProps> = ({initialData}) => {
    const [data, setData] = useState(initialData);
    const [inputValue, setInputValue] = useState('');

    const tableRef = useRef<HTMLDivElement>(null);

    const handleCopyClick = () => {
        if (tableRef.current) {
            const range = document.createRange();
            range.selectNode(tableRef.current);
            window.getSelection()?.removeAllRanges();
            window.getSelection()?.addRange(range);
            document.execCommand('copy');
            window.getSelection()?.removeAllRanges();
        }
    };

    const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setInputValue(event.target.value);
    };

    const handleButtonClick = () => {
        // Call API or perform other action here
    };

    useEffect(() => {
        async function fetchData() {
            try {
                console.log("Gov HK API URL = ", 'https://www.1823.gov.hk/common/ical/en.json');
                const response = await fetch('https://www.1823.gov.hk/common/ical/en.json');
                const data = await response.json();
                console.log('data = ', data);
                setData(data);
            } catch (e) {
                console.log('error = ', e);
            }
        }

        fetchData();
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <TextField id="month" color="warning" label="Month of the Worksheet" variant="standard"/>
                    <div>
                        <a
                            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            By{' '}
                            <Image
                                src="/vercel.svg"
                                alt="Vercel Logo"
                                className={styles.vercelLogo}
                                width={100}
                                height={24}
                                priority
                            />
                        </a>
                    </div>
                </div>
                <button onClick={handleCopyClick}>Copy Table</button>
                <label htmlFor="input-field">Input Value:</label>
                <input type="text" id="input-field" value={inputValue} onChange={handleInputChange}/>
                <button onClick={handleButtonClick}>Submit</button>
                <WSTable desc={inputValue}/>

                <div className={styles.grid}>
                </div>
            </main>
        </>
    )
}


// Home.getInitialProps = async () => {
//   const response = await fetch('https://www.1823.gov.hk/common/ical/en.json');
//   const data = await response.json();
//
//   return { data };
// };

export const getStaticProps: GetStaticProps = async () => {
    const response = await fetch('https://www.1823.gov.hk/common/ical/en.json');
    const data = await response.json();
    return {props: {data}};
};

export default Home